#!/bin/bash
# Generate ed25519 keypair for Tauri auto-update signing.
# Run once, store the private key as a GitHub Secret (TAURI_PRIVATE_KEY).
# The public key goes in tauri.conf.json → plugins.updater.pubkey.

echo "=== Tauri Updater Keypair Generation ==="
echo ""
echo "Install Tauri CLI first: cargo install tauri-cli --version '^2.0.0'"
echo ""
echo "Then run:"
echo "  cargo tauri signer generate -w ~/.tauri/billbook.key"
echo ""
echo "This will output:"
echo "  Private key: saved to ~/.tauri/billbook.key"
echo "  Public key:  dW50cnVzdGVkIGNvbW1l... (a long base64 string)"
echo ""
echo "Add the PRIVATE key as a GitHub Repository Secret:"
echo "  Name:  TAURI_PRIVATE_KEY"
echo "  Value: (contents of ~/.tauri/billbook.key)"
echo ""
echo "Add the PUBLIC key to desktop/tauri.conf.json:"
echo '  "pubkey": "dW50cnVzdGVkIGNvbW1l..."'
echo ""
echo "The latest.json file is auto-generated by tauri-action on each release."
